const DEFAULT_ENTRY_CURRENCY = 'USD';

const DEFAULT_ENTRY_CATEGORY = 'Groceries';

const INITIAL_ENTRY_TYPE = 'expense' as const;

export { DEFAULT_ENTRY_CATEGORY, DEFAULT_ENTRY_CURRENCY, INITIAL_ENTRY_TYPE };
