/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LandingImport } from './routes/landing'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as AnalyticsRouteImport } from './routes/analytics/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as AnalyticsIndexImport } from './routes/analytics/index'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthRecoveryImport } from './routes/auth/recovery'
import { Route as AuthProfileImport } from './routes/auth/profile'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AnalyticsIdImport } from './routes/analytics/$id'

// Create/Update Routes

const LandingRoute = LandingImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AnalyticsRouteRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AnalyticsIndexRoute = AnalyticsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsRouteRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthRecoveryRoute = AuthRecoveryImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthProfileRoute = AuthProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AnalyticsIdRoute = AnalyticsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnalyticsRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingImport
      parentRoute: typeof rootRoute
    }
    '/analytics/$id': {
      id: '/analytics/$id'
      path: '/$id'
      fullPath: '/analytics/$id'
      preLoaderRoute: typeof AnalyticsIdImport
      parentRoute: typeof AnalyticsRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/profile': {
      id: '/auth/profile'
      path: '/profile'
      fullPath: '/auth/profile'
      preLoaderRoute: typeof AuthProfileImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/recovery': {
      id: '/auth/recovery'
      path: '/recovery'
      fullPath: '/auth/recovery'
      preLoaderRoute: typeof AuthRecoveryImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexImport
      parentRoute: typeof AnalyticsRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthRouteImport
    }
  }
}

// Create and export the route tree

interface AnalyticsRouteRouteChildren {
  AnalyticsIdRoute: typeof AnalyticsIdRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
}

const AnalyticsRouteRouteChildren: AnalyticsRouteRouteChildren = {
  AnalyticsIdRoute: AnalyticsIdRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
}

const AnalyticsRouteRouteWithChildren = AnalyticsRouteRoute._addFileChildren(
  AnalyticsRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthRecoveryRoute: typeof AuthRecoveryRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthRecoveryRoute: AuthRecoveryRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/analytics/$id': typeof AnalyticsIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/signup': typeof AuthSignupRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/auth/': typeof AuthIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/analytics/$id': typeof AnalyticsIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/signup': typeof AuthSignupRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/auth': typeof AuthIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/analytics/$id': typeof AnalyticsIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/signup': typeof AuthSignupRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/auth/': typeof AuthIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/landing'
    | '/analytics/$id'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/recovery'
    | '/auth/signup'
    | '/analytics/'
    | '/auth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/analytics/$id'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/recovery'
    | '/auth/signup'
    | '/analytics'
    | '/auth'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/landing'
    | '/analytics/$id'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/recovery'
    | '/auth/signup'
    | '/analytics/'
    | '/auth/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRouteRoute: typeof AnalyticsRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LandingRoute: typeof LandingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRouteRoute: AnalyticsRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LandingRoute: LandingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/analytics",
        "/auth",
        "/landing"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/analytics": {
      "filePath": "analytics/route.tsx",
      "children": [
        "/analytics/$id",
        "/analytics/"
      ]
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/login",
        "/auth/profile",
        "/auth/recovery",
        "/auth/signup",
        "/auth/"
      ]
    },
    "/landing": {
      "filePath": "landing.tsx"
    },
    "/analytics/$id": {
      "filePath": "analytics/$id.tsx",
      "parent": "/analytics"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/auth/profile": {
      "filePath": "auth/profile.tsx",
      "parent": "/auth"
    },
    "/auth/recovery": {
      "filePath": "auth/recovery.tsx",
      "parent": "/auth"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx",
      "parent": "/auth"
    },
    "/analytics/": {
      "filePath": "analytics/index.tsx",
      "parent": "/analytics"
    },
    "/auth/": {
      "filePath": "auth/index.tsx",
      "parent": "/auth"
    }
  }
}
ROUTE_MANIFEST_END */
