packages:
  - packages/*
  - services/*
  - examples/*

catalog:
  react: ^19.0.0
  "react-dom": ^19.0.0
  "@tanstack/react-router": "^1.116.0"
  "@tanstack/react-router-devtools": "^1.116.0"
  "@tanstack/router-plugin": "^1.116.1"
  "@tanstack/react-query": "^5.74.4"
  "@tanstack/react-query-devtools": "4"
  vite: "^6.3.1"
  "@tailwindcss/vite": "^4.1.4"
  "vite-plugin-dts": "^4.5.3"
  "@vitejs/plugin-react-swc": "^3.8.0"
  "@module-federation/vite": "^1.2.6"
  "@clerk/clerk-react": "^5.28.2"
  globals: "^15.15.0"
  eslint: "^9.22.0"
  "@eslint/js": "^9.22.0"
  typescript: "~5.7.2"
  "typescript-eslint": "^8.26.1"
  jsdom: "^26.1.0"
  msw: "^2.8.2"
  "@vitest/coverage-v8": "3.1.2"
  vitest: "^3.1.3"
  "@testing-library/jest-dom": "^6.6.3"
  "@testing-library/react": "^16.3.0"