/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as PlanningIndexImport } from './routes/planning/index'
import { Route as ManagementIndexImport } from './routes/management/index'
import { Route as FinanceIndexImport } from './routes/finance/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as FinanceSettingsIndexImport } from './routes/finance/settings/index'
import { Route as FinancePlanningIndexImport } from './routes/finance/planning/index'
import { Route as FinanceManagementIndexImport } from './routes/finance/management/index'
import { Route as FinanceDashboardIndexImport } from './routes/finance/dashboard/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

const PlanningIndexRoute = PlanningIndexImport.update({
  id: '/planning/',
  path: '/planning/',
  getParentRoute: () => rootRoute,
} as any)

const ManagementIndexRoute = ManagementIndexImport.update({
  id: '/management/',
  path: '/management/',
  getParentRoute: () => rootRoute,
} as any)

const FinanceIndexRoute = FinanceIndexImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const FinanceSettingsIndexRoute = FinanceSettingsIndexImport.update({
  id: '/finance/settings/',
  path: '/finance/settings/',
  getParentRoute: () => rootRoute,
} as any)

const FinancePlanningIndexRoute = FinancePlanningIndexImport.update({
  id: '/finance/planning/',
  path: '/finance/planning/',
  getParentRoute: () => rootRoute,
} as any)

const FinanceManagementIndexRoute = FinanceManagementIndexImport.update({
  id: '/finance/management/',
  path: '/finance/management/',
  getParentRoute: () => rootRoute,
} as any)

const FinanceDashboardIndexRoute = FinanceDashboardIndexImport.update({
  id: '/finance/dashboard/',
  path: '/finance/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceIndexImport
      parentRoute: typeof rootRoute
    }
    '/management/': {
      id: '/management/'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementIndexImport
      parentRoute: typeof rootRoute
    }
    '/planning/': {
      id: '/planning/'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/finance/dashboard/': {
      id: '/finance/dashboard/'
      path: '/finance/dashboard'
      fullPath: '/finance/dashboard'
      preLoaderRoute: typeof FinanceDashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/finance/management/': {
      id: '/finance/management/'
      path: '/finance/management'
      fullPath: '/finance/management'
      preLoaderRoute: typeof FinanceManagementIndexImport
      parentRoute: typeof rootRoute
    }
    '/finance/planning/': {
      id: '/finance/planning/'
      path: '/finance/planning'
      fullPath: '/finance/planning'
      preLoaderRoute: typeof FinancePlanningIndexImport
      parentRoute: typeof rootRoute
    }
    '/finance/settings/': {
      id: '/finance/settings/'
      path: '/finance/settings'
      fullPath: '/finance/settings'
      preLoaderRoute: typeof FinanceSettingsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/management': typeof ManagementIndexRoute
  '/planning': typeof PlanningIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/finance/dashboard': typeof FinanceDashboardIndexRoute
  '/finance/management': typeof FinanceManagementIndexRoute
  '/finance/planning': typeof FinancePlanningIndexRoute
  '/finance/settings': typeof FinanceSettingsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/management': typeof ManagementIndexRoute
  '/planning': typeof PlanningIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/finance/dashboard': typeof FinanceDashboardIndexRoute
  '/finance/management': typeof FinanceManagementIndexRoute
  '/finance/planning': typeof FinancePlanningIndexRoute
  '/finance/settings': typeof FinanceSettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/planning/': typeof PlanningIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/finance/dashboard/': typeof FinanceDashboardIndexRoute
  '/finance/management/': typeof FinanceManagementIndexRoute
  '/finance/planning/': typeof FinancePlanningIndexRoute
  '/finance/settings/': typeof FinanceSettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/finance'
    | '/management'
    | '/planning'
    | '/settings'
    | '/finance/dashboard'
    | '/finance/management'
    | '/finance/planning'
    | '/finance/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/finance'
    | '/management'
    | '/planning'
    | '/settings'
    | '/finance/dashboard'
    | '/finance/management'
    | '/finance/planning'
    | '/finance/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/finance/'
    | '/management/'
    | '/planning/'
    | '/settings/'
    | '/finance/dashboard/'
    | '/finance/management/'
    | '/finance/planning/'
    | '/finance/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  ManagementIndexRoute: typeof ManagementIndexRoute
  PlanningIndexRoute: typeof PlanningIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  FinanceDashboardIndexRoute: typeof FinanceDashboardIndexRoute
  FinanceManagementIndexRoute: typeof FinanceManagementIndexRoute
  FinancePlanningIndexRoute: typeof FinancePlanningIndexRoute
  FinanceSettingsIndexRoute: typeof FinanceSettingsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  ManagementIndexRoute: ManagementIndexRoute,
  PlanningIndexRoute: PlanningIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  FinanceDashboardIndexRoute: FinanceDashboardIndexRoute,
  FinanceManagementIndexRoute: FinanceManagementIndexRoute,
  FinancePlanningIndexRoute: FinancePlanningIndexRoute,
  FinanceSettingsIndexRoute: FinanceSettingsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard/",
        "/finance/",
        "/management/",
        "/planning/",
        "/settings/",
        "/finance/dashboard/",
        "/finance/management/",
        "/finance/planning/",
        "/finance/settings/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/finance/": {
      "filePath": "finance/index.tsx"
    },
    "/management/": {
      "filePath": "management/index.tsx"
    },
    "/planning/": {
      "filePath": "planning/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    },
    "/finance/dashboard/": {
      "filePath": "finance/dashboard/index.tsx"
    },
    "/finance/management/": {
      "filePath": "finance/management/index.tsx"
    },
    "/finance/planning/": {
      "filePath": "finance/planning/index.tsx"
    },
    "/finance/settings/": {
      "filePath": "finance/settings/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
