const STREAM_FRAME_SEPARATOR = '\n\n';
const STREAM_LINE_SEPARATOR = '\n';
const STREAM_DEFAULT_EVENT_NAME = 'message';
const STREAM_DEFAULT_METHOD = 'GET';

const STREAM_COMMENT_PREFIX = ':';
const STREAM_FIELD_SEPARATOR = ':';

const EVENT_FIELD_NAME = 'event';
const IDENTIFIER_FIELD_NAME = 'id';
const DATA_FIELD_NAME = 'data';

export {
	DATA_FIELD_NAME,
	EVENT_FIELD_NAME,
	IDENTIFIER_FIELD_NAME,
	STREAM_COMMENT_PREFIX,
	STREAM_DEFAULT_EVENT_NAME,
	STREAM_DEFAULT_METHOD,
	STREAM_FIELD_SEPARATOR,
	STREAM_FRAME_SEPARATOR,
	STREAM_LINE_SEPARATOR,
};
