const QUERY_KEYS = {
	wallets: 'wallets',
	walletsSearch: 'searchWallet',
	wallet: 'wallet',
	goals: 'goals',
	goalsSearch: 'searchGoal',
	goal: 'goal',
	transactions: 'transactions',
	transactionsSearch: 'transactionsSearch',
	transaction: 'transaction',
	accounts: 'accounts',
	account: 'account',
	accountEntries: 'account-entries',
	actions: 'actions',
	automations: 'automations',
	automationsSearch: 'searchAutomation',
	automation: 'automation',
	notifications: 'notifications',
	notificationsCount: 'notifications-count',
	webhooks: 'webhooks',
	webhook: 'webhook',
	webhookEventTypes: 'webhook-event-types',
	webhookSubscriptions: 'webhook-subscriptions',
	webhookDeliveries: 'webhook-deliveries',
	assistantOverview: 'assistant-overview',
	assistantMessages: 'assistant-messages',
	session: 'auth-session',
	metrics: 'metrics',
} as const;

export { QUERY_KEYS };
