const ALLOWED_CHARACTERS_PATTERN = /[^0-9.]/g;
const GROUP_BOUNDARY_PATTERN = /\B(?=(\d{3})+(?!\d))/g;

const DECIMAL_SEPARATOR = '.';
const GROUP_SEPARATOR = ',';
const ZERO = '0';

export {
	ALLOWED_CHARACTERS_PATTERN,
	DECIMAL_SEPARATOR,
	GROUP_BOUNDARY_PATTERN,
	GROUP_SEPARATOR,
	ZERO,
};
