const MOCK_LATENCY = 250;
const CURSOR_VERSION = 'v1';
const DEFAULT_PAGE_LIMIT = 25;
const MIN_PAGE_LIMIT = 1;
const MAX_PAGE_LIMIT = 100;

export { MOCK_LATENCY, CURSOR_VERSION, DEFAULT_PAGE_LIMIT, MIN_PAGE_LIMIT, MAX_PAGE_LIMIT };
