const WRITE_VERSION_HEADER = 'X-Write-Version';
const READ_AT_LEAST_HEADER = 'Read-At-Least';
const IDEMPOTENCY_HEADER = 'Idempotency-Key';
const LAST_EVENT_ID_HEADER = 'Last-Event-ID';

const JSON_CONTENT_TYPE = 'application/json';
const EVENT_STREAM_CONTENT_TYPE = 'text/event-stream';

const STREAM_FRAME_SEPARATOR = '\n\n';
const STREAM_LINE_SEPARATOR = '\n';
const STREAM_DEFAULT_EVENT = 'message';
const STREAM_DEFAULT_METHOD = 'GET';

const QUERY_ARRAY_SEPARATOR = ',';

export {
	EVENT_STREAM_CONTENT_TYPE,
	IDEMPOTENCY_HEADER,
	JSON_CONTENT_TYPE,
	LAST_EVENT_ID_HEADER,
	QUERY_ARRAY_SEPARATOR,
	READ_AT_LEAST_HEADER,
	STREAM_DEFAULT_EVENT,
	STREAM_DEFAULT_METHOD,
	STREAM_FRAME_SEPARATOR,
	STREAM_LINE_SEPARATOR,
	WRITE_VERSION_HEADER,
};
