const WRITE_VERSION_HEADER = 'X-Write-Version';
const READ_AT_LEAST_HEADER = 'Read-At-Least';
const IDEMPOTENCY_HEADER = 'Idempotency-Key';
const IDEMPOTENT_REPLAYED_HEADER = 'Idempotent-Replayed';
const LAST_EVENT_ID_HEADER = 'Last-Event-ID';
const RETRY_AFTER_HEADER = 'Retry-After';
const RATE_LIMIT_LIMIT_MINUTE_HEADER = 'X-RateLimit-Limit-Minute';
const RATE_LIMIT_REMAINING_MINUTE_HEADER = 'X-RateLimit-Remaining-Minute';
const RATE_LIMIT_LIMIT_HOUR_HEADER = 'X-RateLimit-Limit-Hour';
const RATE_LIMIT_REMAINING_HOUR_HEADER = 'X-RateLimit-Remaining-Hour';

const JSON_CONTENT_TYPE = 'application/json';
const EVENT_STREAM_CONTENT_TYPE = 'text/event-stream';

const STREAM_FRAME_SEPARATOR = '\n\n';
const STREAM_LINE_SEPARATOR = '\n';
const STREAM_DEFAULT_EVENT = 'message';
const STREAM_DEFAULT_METHOD = 'GET';

const QUERY_ARRAY_SEPARATOR = ',';

export {
	EVENT_STREAM_CONTENT_TYPE,
	IDEMPOTENCY_HEADER,
	IDEMPOTENT_REPLAYED_HEADER,
	JSON_CONTENT_TYPE,
	LAST_EVENT_ID_HEADER,
	QUERY_ARRAY_SEPARATOR,
	RATE_LIMIT_LIMIT_HOUR_HEADER,
	RATE_LIMIT_LIMIT_MINUTE_HEADER,
	RATE_LIMIT_REMAINING_HOUR_HEADER,
	RATE_LIMIT_REMAINING_MINUTE_HEADER,
	READ_AT_LEAST_HEADER,
	RETRY_AFTER_HEADER,
	STREAM_DEFAULT_EVENT,
	STREAM_DEFAULT_METHOD,
	STREAM_FRAME_SEPARATOR,
	STREAM_LINE_SEPARATOR,
	WRITE_VERSION_HEADER,
};
