const WRITE_VERSION_HEADER = 'X-Write-Version';
const READ_AT_LEAST_HEADER = 'Read-At-Least';
const IDEMPOTENCY_HEADER = 'Idempotency-Key';
const IDEMPOTENT_REPLAYED_HEADER = 'Idempotent-Replayed';
const LAST_EVENT_ID_HEADER = 'Last-Event-ID';
const RETRY_AFTER_HEADER = 'Retry-After';
const AUTHORIZATION_HEADER = 'Authorization';
const ACCEPT_HEADER = 'Accept';
const CONTENT_TYPE_HEADER = 'Content-Type';
const RATE_LIMIT_LIMIT_MINUTE_HEADER = 'X-RateLimit-Limit-Minute';
const RATE_LIMIT_REMAINING_MINUTE_HEADER = 'X-RateLimit-Remaining-Minute';
const RATE_LIMIT_LIMIT_HOUR_HEADER = 'X-RateLimit-Limit-Hour';
const RATE_LIMIT_REMAINING_HOUR_HEADER = 'X-RateLimit-Remaining-Hour';

export {
	ACCEPT_HEADER,
	AUTHORIZATION_HEADER,
	CONTENT_TYPE_HEADER,
	IDEMPOTENCY_HEADER,
	IDEMPOTENT_REPLAYED_HEADER,
	LAST_EVENT_ID_HEADER,
	RATE_LIMIT_LIMIT_HOUR_HEADER,
	RATE_LIMIT_LIMIT_MINUTE_HEADER,
	RATE_LIMIT_REMAINING_HOUR_HEADER,
	RATE_LIMIT_REMAINING_MINUTE_HEADER,
	READ_AT_LEAST_HEADER,
	RETRY_AFTER_HEADER,
	WRITE_VERSION_HEADER,
};
