const SOCKET_TOKEN_MARKER = 'clerk';

const SOCKET_SANDBOX_PARAM = 'sandbox';

const UNSUPPORTED_FRAME_CODE = 1003;

const NORMAL_CLOSURE_CODE = 1000;

const SECURE_HTTP_PROTOCOL = 'https:';
const SECURE_SOCKET_PROTOCOL = 'wss:';
const SOCKET_PROTOCOL = 'ws:';

export {
	NORMAL_CLOSURE_CODE,
	SECURE_HTTP_PROTOCOL,
	SECURE_SOCKET_PROTOCOL,
	SOCKET_PROTOCOL,
	SOCKET_SANDBOX_PARAM,
	SOCKET_TOKEN_MARKER,
	UNSUPPORTED_FRAME_CODE,
};
