"use strict";
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.routeTree = void 0;
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
// Import Routes
var __root_1 = require("./../services/finance/src/app/routes/__root");
var main_1 = require("./../services/finance/src/app/routes/main");
var overview_1 = require("../services/finance/src/app/routes/overview");
var overview_2 = require("../services/finance/src/app/routes/overview");
// Create/Update Routes
var MainRoute = main_1.Route.update({
    id: '/main',
    path: '/main',
    getParentRoute: function () { return __root_1.Route; },
});
var AboutRoute = overview_1.Route.update({
    id: '/about',
    path: '/about',
    getParentRoute: function () { return __root_1.Route; },
});
var IndexRoute = overview_2.Route.update({
    id: '/',
    path: '/',
    getParentRoute: function () { return __root_1.Route; },
});
var rootRouteChildren = {
    IndexRoute: IndexRoute,
    AboutRoute: AboutRoute,
    MainRoute: MainRoute,
};
exports.routeTree = __root_1.Route
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/main"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/main": {
      "filePath": "main.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
